### ISSUE TITLE
Fails with PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by croepha** [jquast/blessed#84]
Works:
```
$ python
Python 3.5.0 (default, Sep 23 2015, 04:42:00)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import blessed
>>>
```
Doesn't work:
```
$ PYTHONOPTIMIZE=2 python
Python 3.5.0 (default, Sep 23 2015, 04:42:00)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import blessed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidbutler/projects/misc/blessed/blessed/__init__.py", line 10, in <module>
    from blessed.terminal import Terminal
  File "/Users/davidbutler/projects/misc/blessed/blessed/terminal.py", line 63, in <module>
    from .sequences import (SequenceTextWrapper,
  File "/Users/davidbutler/projects/misc/blessed/blessed/sequences.py", line 244, in <module>
    class Sequence(six.text_type):
  File "/Users/davidbutler/projects/misc/blessed/blessed/sequences.py", line 341, in Sequence
    """)
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
>>>
```

**Comment by jquast** [comment]
I guess part of optimization is ripping out docstrings, for which the deriving implementation is not able to augment.

I suppose the fix would be to lift python's core documentation in-place. Thanks.

https://github.com/jquast/blessed/blob/master/blessed/sequences.py#L329-L341

**Comment by jquast** [comment]
see http://bugs.python.org/issue23189

**Comment by croepha** [comment]
Well, Travis has an issue, I don't think its related, but maybe something like this will be a good fix: https://github.com/jquast/blessed/pull/85

**Comment by jquast** [comment]
Apology for the delay in releasing, but this fix is now on pypi.
